---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "warehouse-web-deployment"
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: "warehouse-web"
  replicas: 1
  template:
    metadata:
      labels:
        app: "warehouse-web"
    spec:
      containers:
        - image: ${IMAGE}
          imagePullPolicy: Always
          name: "warehouse-web"
          ports:
            - containerPort: 80
          env:
            - name: TESTNAME
              value: TESTVALUE
          envFrom:
            - secretRef:
                name: ${NAMESPACE}-env
