# Credentials for http://www.ncdc.noaa.gov/cdo-web/webservices/v2
<%= ENV['RAILS_ENV'] %>:
  email: <%= ENV['WEATHER_EMAIL'] %>
  token: <%= ENV['WEATHER_TOKEN'] %>
  darksky: <%= ENV['WEATHER_DARKSKY'] %>