version: '3'
services:
  web:
    image: $IMAGE
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: openpath-ecs
        awslogs-region: us-east-1
        awslogs-stream-prefix: web